package export

import (
	"encoding/csv"
	"encoding/json"
	"fmt"
	"io"
	"math"
	"strconv"
	"strings"
	"time"

	"github.com/bakhod1r/seedora/internal/ddl"
	"github.com/bakhod1r/seedora/internal/model"
)

// The column order is the plan's, not the map's, in every format. A fixture
// regenerated with the same seed should be byte-identical to the last one, and
// Go's map iteration order guarantees it would not be.

func writeCSV(w io.Writer, t *model.Table, cols []string, rows []map[string]any) error {
	scales := scalesOf(t, cols)
	out := csv.NewWriter(w)
	if err := out.Write(cols); err != nil {
		return err
	}
	record := make([]string, len(cols))
	for _, row := range rows {
		for i, c := range cols {
			record[i] = csvValue(round(row[c], scales[c]))
		}
		if err := out.Write(record); err != nil {
			return err
		}
	}
	out.Flush()
	return out.Error()
}

// csvValue renders one cell. NULL is the empty field, which is what Postgres's
// COPY and MySQL's LOAD DATA both read back as NULL by default — the point of
// the file is that a bulk loader can take it.
func csvValue(v any) string {
	if v == nil {
		return ""
	}
	switch t := v.(type) {
	case string:
		return t
	case []byte:
		return string(t)
	case time.Time:
		return t.Format(time.RFC3339Nano)
	case bool:
		return strconv.FormatBool(t)
	case float64:
		return strconv.FormatFloat(t, 'f', -1, 64)
	case float32:
		return strconv.FormatFloat(float64(t), 'f', -1, 32)
	}
	return fmt.Sprint(v)
}

func writeJSON(w io.Writer, t *model.Table, cols []string, rows []map[string]any) error {
	scales := scalesOf(t, cols)
	enc := json.NewEncoder(w)
	enc.SetIndent("", "  ")

	// Built as ordered pairs rather than handed the map, so the keys come out
	// in the table's column order instead of alphabetically.
	out := make([]json.RawMessage, 0, len(rows))
	for _, row := range rows {
		var b strings.Builder
		b.WriteByte('{')
		for i, c := range cols {
			if i > 0 {
				b.WriteByte(',')
			}
			name, err := json.Marshal(c)
			if err != nil {
				return err
			}
			value, err := json.Marshal(jsonValue(round(row[c], scales[c])))
			if err != nil {
				return fmt.Errorf("column %s: %w", c, err)
			}
			b.Write(name)
			b.WriteByte(':')
			b.Write(value)
		}
		b.WriteByte('}')
		out = append(out, json.RawMessage(b.String()))
	}
	return enc.Encode(out)
}

// jsonValue keeps a timestamp readable and a byte slice from becoming base64,
// which is what encoding/json does with one by default and is not what anybody
// loading a fixture expects to find.
func jsonValue(v any) any {
	switch t := v.(type) {
	case []byte:
		return string(t)
	case time.Time:
		return t.Format(time.RFC3339Nano)
	}
	return v
}

func writeSQL(w io.Writer, t *model.Table, cols []string, rows []map[string]any, dialect ddl.Dialect) error {
	scales := scalesOf(t, cols)
	if len(rows) == 0 {
		_, err := fmt.Fprintf(w, "-- %s: no rows\n", t.Name)
		return err
	}

	// Identifiers are quoted the way ddl does it, so the file runs on a session
	// nobody configured — the same reason an exported schema.sql uses backticks
	// on MySQL rather than the double quotes the seeder's own connection sets up.
	quoted := make([]string, len(cols))
	for i, c := range cols {
		quoted[i] = ddl.QuoteIdent(dialect, c)
	}
	head := fmt.Sprintf("INSERT INTO %s (%s) VALUES\n",
		ddl.QuoteIdent(dialect, t.Name), strings.Join(quoted, ", "))

	if _, err := io.WriteString(w, head); err != nil {
		return err
	}

	// One statement, one row per line. A statement per row would be correct and
	// an order of magnitude slower to replay; a single statement of a hundred
	// thousand rows is what the engines are built to take.
	var b strings.Builder
	for i, row := range rows {
		b.Reset()
		b.WriteString("  (")
		for j, c := range cols {
			if j > 0 {
				b.WriteString(", ")
			}
			b.WriteString(sqlLiteral(round(row[c], scales[c])))
		}
		b.WriteByte(')')
		if i == len(rows)-1 {
			b.WriteString(";\n")
		} else {
			b.WriteString(",\n")
		}
		if _, err := io.WriteString(w, b.String()); err != nil {
			return err
		}
	}
	return nil
}

// sqlLiteral renders a value as SQL.
//
// Everything that is not a number, a boolean, or NULL is quoted as a string
// with its quotes doubled. That is the one escape every engine here agrees on,
// and the values being rendered were generated by Seedora rather than supplied
// by anyone — but the escaping is done properly regardless, because a fixture
// file is a thing people edit and then re-run.
func sqlLiteral(v any) string {
	if v == nil {
		return "NULL"
	}
	switch t := v.(type) {
	case bool:
		if t {
			return "TRUE"
		}
		return "FALSE"
	case int, int8, int16, int32, int64, uint, uint8, uint16, uint32, uint64:
		return fmt.Sprint(t)
	case float64:
		return strconv.FormatFloat(t, 'f', -1, 64)
	case float32:
		return strconv.FormatFloat(float64(t), 'f', -1, 32)
	case time.Time:
		return quote(t.Format(time.RFC3339Nano))
	case []byte:
		return quote(string(t))
	case string:
		return quote(t)
	}
	return quote(fmt.Sprint(v))
}

func quote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", "''") + "'"
}

// scalesOf reads the declared decimal scale of each column, 0 where the column
// is not a fixed-scale number.
func scalesOf(t *model.Table, cols []string) map[string]int {
	out := make(map[string]int, len(cols))
	if t == nil {
		return out
	}
	for _, name := range cols {
		if c := t.Column(name); c != nil && c.Scale > 0 {
			out[name] = c.Scale
		}
	}
	return out
}

// round trims a float to the scale its column declares.
//
// A DECIMAL(10,2) column holds two decimal places, and the database would have
// rounded the value on the way in. Writing the generator's full binary float
// into the file instead produces a fixture that does not match what seeding the
// same plan would have stored — and, on a loader that checks rather than
// rounds, one that does not load at all.
func round(v any, scale int) any {
	if scale <= 0 {
		return v
	}
	pow := math.Pow(10, float64(scale))
	switch f := v.(type) {
	case float64:
		return math.Round(f*pow) / pow
	case float32:
		return math.Round(float64(f)*pow) / pow
	}
	return v
}
